version: "3.8"
services:
  postgres:
    image: postgres
    container_name: postgres-db # the name of the container is postgres-db, not postgres. This is the one used 
    environment:
      POSTGRES_USER: kestra
      POSTGRES_PASSWORD: k3str4
      POSTGRES_DB: postgres-zoomcamp
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: